<?php echo $this->doctype('HTML5'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<?php echo $this->headTitle('Add User'); ?>
	</head>
	<body>
		<?php echo $this->render('includes/header.phtml') ?>
		<h3>Add Artist</h3>
		<p>
			Thank you. The artist has successfully saved.<br/>
			<a href='new'>Add another user</a>
		</p>
	</body>
</html>
<!--<br /><br />
<div id="view-content">
	<p>View script for controller <b>Account</b> and script/action name <b>success</b></p>
</div>-->
